- hosts: localhost
  pre_tasks:
  - name: Update Apt
    become: true
    ansible.builtin.apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/zsh-setup.yml
    - include: tasks/core-setup.yml
    - include: tasks/git-setup.yml
    - include: tasks/dotfiles.yml
    - include: tasks/productivity-tools.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/brave.yml
    - include: tasks/docker.yml
    - include: tasks/flatpak-apps.yml



