- name: Installing stow
  become: true
  ansible.builtin.apt: 
    name: stow
  tags:
    - dotfiles
    - stow
    - install

- name: Cloning .dotfiles
  shell: |
    git clone git@github.com:guventmz/.dotfiles.git ~/.dotfiles
          # eval $(ssh-agent)
          # ssh-add {{ dest_key }}
    #ansible.builtin.git:
    #  repo: "git@github.com:guventmz/.dotfiles.git"
    #  dest: "{{ lookup('env', 'HOME') }}/.dotfiles_testttt"
    #  recursive: yes
    #  update: yes
    #  accept_hostkey: yes
    #  version: main
    #  key_file: "{{ dest_key }}"
  tags:
    - dotfiles
    - stow
    - install

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu.sh
  tags:
    - dotfiles
    - stow
    - install
