- name: Installing stow
  become: true
  ansible.builtin.apt: 
    name: stow
  tags:
    - dotfiles
    - stow
    - install

- name: Cloning .dotfiles
  shell: git clone git@github.com:guventmz/.dotfiles.git ~/.dotfiles
  tags:
    - dotfiles
    - stow
    - install

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu.sh
  tags:
    - dotfiles
    - stow
    - install
