- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - neovim
    - install

- name: Get Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - neovim
    - install

- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - neovim
    - install

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
  tags:
    - neovim
    - install

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - neovim
    - install
