- name: Install productivity packages. (tmux, fzf, xsel, tldr etc.)
  become: true
  apt:
    name: 
      - tmux 
      - fzf 
      - xsel 
      - tldr 
      - ripgrep
      - "mysql-client"
      - pspg
  tags:
    - install
    - productivity
